const translations = {
    en: {
        contactanos:"Contact Us",
        click_aqui:"Click Here",
        desayuno_hoteles:"Breakfast Hotel",
        promociones: "Promotions",
        escoge_idioma:"Choose a language",
        desayunos: "Breakfast",
        clasicos: "Classics",
        plato_fruta: "Fruit Plate", 
        plato_fruta_d: "The best selection of fresh seasonal fuits, yogurt and granola. 420g",
        french_toast_d: "Delicious homemade french bread made with powdered sugar, banana and maple syrup",
        hot_cake_d: "3 pieces of unbeatable hot cake with banana, strawberry and bee honey. 300 g",
        chia_bowl_d:"Delicious almond milk with granola, strawberry, chia and kiw, ideal to start a healthy day. 400 g",
        burrito_d:"30cm diameter wheat tortilla filled with succulent Mexican style eggs, rice, beans, and cheese. 450g",
        waffles_d: "Tasty waffles in four pieces accompanied by the best cambination of banana, strawberry and vanilla ice cream. 450g",
        croissant_d:"House made, served with butter ang honey. 60g",

        tostadas:"Toast",
        tostada_aguacate:"Avocado Toast",
        tostada_aguacate_d:"A crispy toast with p poached egg, avocado and arugula. 280g.",
        tostada_salmon:"Salmon Toast",
        tostada_salmon_d:"A crispy toast with smoked salmon, capers and fried pore. 280 g",
        tostada_vegetariana:"Vegetarian Toast",
        tostada_vegetariana_d:"A crispy toast with grilled vegetables and vegan cheese. 280g",
        huevos:"Eggs",
        huevos_rancheros_d:"Sensational fried eggs, ranchera sauce and corn toast. 400g",
        huevos_gusto:"Eggs to taste",
        huevos_gusto_d:"Freshly prepared eggs: omelette, fried or scrambled. 350g",
        huevos_benedictinos: "Benedict Eggs",
        huevos_benedictinos_d:"Delicius hamemade bread with turkey ham and hollandaise sauce. 350g",
        sandwich_huevo: "Eggs sandwich",
        sandwich_huevo_d:"Homemade bread with egg, avocado and bacon. 400g",
        chilaquiles_d:"Delicious Mexican dish with corn tortilla chips in red or green sause served with milk cream, cotija cheese, red onion and cilatro. 420g",
        extra:"*Extras. 50g: With eggs $25, chicken $45 or arrachera $55, beans $50, rice, $50",

        lunch_cena:"Lunch / Dinner",
        entradas:"Appetizers",
        guacamole_d:"Succulent prehispanic salsa made with avocado, tomato, onion, cilantro and jalapeño. 280 g",
        empanadas_horneadas:"Baked Empanadas",
        empanadas_horneadas_d:"(2pcs. to choose) Fiery empanadas baked in a wood-fired oven, with the best variety: Arrachera, spinach, capresse or chicken. 185g",
        mina_ceviche:"Mina Ceviche",
        mina_ceviche_d:"Abundant mix of fresh seafood and fish: octopus, grouper and shrimp. With onion, avocado, tomato and cilantro marinated in lime. 250g",
        tostada_atun:"Tuna Tostada",
        tostada_atun_d:"A marinated toast with capers, fresh, celery, apple and tuna. 250g",
        
        ensaladas:"Salads",
        capresse_d:"The original recipe with fresh mozzarella cheese, pesto and basil. 220g",
        cesar:"Caesar",
        cesar_d:"Fresh salad with shredded lettuce and caeser dessing, croutons and parmesan cheese. 220g",
        betabel:"Beet",
        betabel_d:"Nutrient-rich salad with blue cheese dressing, yogurt and candied walnuts. 220g",

        vegetariano_vegano:"Vegetarian / Vegan",
        croquetas_camote:"Sweet Potato Croquettes",
        croquetas_camote_d:"Rich combination of flavors, 4 sweet potato croquettes stuffed with parmesan cheese in a mirror of pineapple gravy sauce with a touch of jalapeño mayonnaise. 300 g",
        berenjena_asada_vegana:"Vegan Roasted Eggplant",
        berenjena_asada_vegana_d:"Nutritious balsamic cured eggplant topped with sesame paste with paprika and crispy chickpea and arugula salad with cherry tomato and a balsamic concentrate. 250 g",
        taco_pastor_vegano:"Vegan Pastor's Taco",
        taco_pastor_vegano_d:"Healthy sweet potato with achiote sauce, grilled pineapple, corn tortilla, cilantro, onion and lime. 200g",
        pasta_calabaza:"Zucchini Pasta",
        pasta_calabaza_d:"Soft spaghetti made with a rich white wine butter sauce served with toasted bread, cherry tomatoes, cilantro, onion, lime and parmesan chesse. 300g",
        pescado_tempura:"Tempura Fish",
        pescado_tempura_d:"Unbeatable dish with 4 corn tortillas, cabbage salad and avocado sauce. Fish. 320g",
        arrachera_d:"Authentic dish with 4 corn tortillas, onion, cilantro and avocado sauce. Arrachera. 320 g",
        pastor_d:"Appetezing dish with 4 corn tortillas, onion, cilantro and pineapple. Pastor 320 g",
        cochinita_d:"Hot dish with 4 corn tortillas and pickled red onion. Cochinita 320 g",
        camaron:"Shrimp",
        camaron_d:"Colorful dish and unique combination of flavors with 4 flour tortillas, grated cucumber, grated carrot and a rich tamarind sauce. Shrimp 320g.",
        salmon:"Salmon",
        salmon_d:"Rich combination with Ponsu sauce, carrot and cucumber salad, chipotle mayonnaise and fresh salmon with 4 corn tortillas. Salmon 180 g",
        pollo:"Chicken",
        pollo_d:"Original grillled chicken taco with chimichurri, white onion, cilantro and house sauce with 4 corn tortillas. Chicken 200g",

        hamburguesa_mina:"MINA Burger",
        hamburguesa_mina_d:"Rich 100% beef(320 g) in brioche bun, with caramelized onion, caramelized apple, bacon and grilled cheese. Served with french fries. 180g",
        costilla_bbq:"BBQ Rib",
        costilla_bbq_d:"Juicy pork rib (300 g) bathed in our exquisite homemade bbq sauce. Served with sweet corn",
        alitas_bbq:"BBQ Wings",
        alitas_bbq_d:"7 pieces of wood-fired baked or fried wings covered with BBQ sauce. 180g",
        filete_pescado:"Fish Fillet",
        filete_pescado_d:"Snook fillet (200g) in lemon sauce, house rustic sweet potato puree and vegetables. 280g",
        atun_empanizado:"Breaded Tuna",
        atun_empanizado_d:"Divine Ensenada tuna fillet (200 g) seared in sesame crust with grilled vegtables. 280 g",
        salmon_glaseado:"Glazed Salmon",
        salmon_glaseado_d:"Wood-fired salmon fillet (200 g) with mashed potatoes, grilled vegetables and balsamic sauce. 280g",
        pescado_entero:"Whole Fish",
        pescado_entero_d:"Baked or wood-fired catch of the day, served with mashed potatoes, vegetables, french fries and mixed salad. 1,800 g",
        camarones_gusto:"Shrimp to taste",
        camarones_gusto_d:"6 pieces of the largest shrimp with 2 garnishes of your choice. 200g",
        pulpo_gallega:"Galician Style Octupus",
        pulpo_gallega_d:"Galician style octopus, seasonned in the best MINA style and served with potatoes with fine herbs. 350 g",
        parrillada_mina:"Mina Grill",
        parrillada_mina_d:"Celestial grill for two peopple with octopus, seasoned, in the best MINA style and served with potatoes with fine herbs. 350 g.",
        filete_mignon:"Filet Mignon",
        filete_mignon_d:"Sumptous medallions (250 g) with mashed potatoes, grilled asparagus and red wine sauce. 280 g",
        rib_eye_d:"Selection of prime beef (400 g) and garnish. 250g",
        mar_tierra:"Surf and Turf",
        mar_tierra_d:"Fiery grilled with fresh jumbo shrimp (250 g), premium beef fillet (200 g) and rice or grilled veggerables.",
        langosta:"Lobster",
        langosta_d:"(Seasonal) Choice of garnish. *Choice of garnish: Mashed potato, vegetables, mixed",

        margarita_d:"Succulent crispy pizza cooked in a wood-fired oven with tomato sauce, mozzarella cheese, basil. 250 g of dough and 320 g of ingredients.",
        arugula_d:"Succulent crispy pizza cooked in a wood-fired oven with tomato sauce, mozzarella cheese, proscuitto, arugula and parmesan. 250 g of dough and 320 g of ingredients",
        pepperoni_d:"Succulent crispy pizza cooked in a wood-fired oven with tomato sauce, mozarella cheese and pepperoni. 250 g of dough and 320 g of ingredients.",
        cuatro_quesos:"4 Cheeses",
        cuatro_quesos_d:"Succulent crispy pizza cooked in a wood-fired oven with tomato sauce, mozzarella cheese, blue cheese, Monterey cheese and parmesan cheese. 250 g of dough and 320 g of ingredients",
        ingrediente_adicional:"Additional ingredient 80g",
        fettuchini_alfredo_p:"Tempting fettuccine pasta with ham, bacon and house sauce. 420 g",
        frutti_di_mare_d:"The favorite of the beach. Delicious fettucchini (200 g) with white wine, butter and seafood. Shrimp (100 g), mussel (60 g), clam (60 g) and octupus (70 g)",
        pomodoro_d:"From our Italian secret recipe. Fettuccini with house sauce and spices. 420 g",
        postres:"Desserts",
        volcan_dulce_leche:"Dulce de Leche Volcano",
        volcan_dulce_leche_d:"Rich melt-in-your-mouth dessert with dulce de leche base, vanilla ice cream and artificial coral. 210 g",
        churros_d:"Sweet fried snacks made of wheat flour sprinkled with sugar, accompanied by vanilla ice cream and chocolate syrub. 210 g",
        brownie_d:"Fudgy chocolate brownie, served with 1 scoop of ice cream (flavor of your choice). 210 g",
        copa_helado:"Ice Cream Cup",
        copa_helado_d:"Splendid cup with 2 scoops of ice cream (vanilla of chocolate). Bathed with the richest syrup. 70g",
        bread_basket:"Bread basket",
        pollo:"Chicken",
        aguacate:"Avocado",
        huevo:"Eggs",
        camaron:"Shrimp",
        salmon:"Salmon",
        tocino:"Bacon",
        vegetales:"Vegetables",
        papas_francesa:"French Fries",
        scoop_helado:"Ice Cream Scoop 100 g",
        para_llevar:"Take-away",
        para_llevar_d:"Container",
        para_llevar_cafe_d:"Coffe to go cup",
        descorche:"Corkage Service",
        descorche_d:"Any liquor by the bottle",

        ninos:"Kids",
        nuggets_pollo:"Chicken Nuggets",
        nuggets_pollo_d:"5 pcs. of juicy breaded chicken breast (105 g) with french fries",
        macarrones_queso:"Macaroni with Cheese",
        macarrones_queso_d:"House pasta with cheddar and parmesan cheese. 150 g",
        bebidas:"Drinks",
        cafe:"Coffee",
        capuchino:"Cappuccino",
        doble_expresso:"Double espresso",
        leche_almendra:"Almond milk",
        leche_avena:"Soy Milk",
        cafe_frio:"Cold Coffe",
        te:"Tea",
        vaso_leche:"Glass of Milk",
        jugos:"Juices",
        naranja:"Orange",
        toronja:"Grapefruit",
        fresa:"Strawberry",
        pina:"Pineapple",
        green_spring_d:"Green juice made with the freshest ingredients, cucumber, spinach, orange juice, pineapple, green apple, celery. Fresh and healthy.",
        love_colada_d:"Creamy drink made with strawberry, almonds, oats, coconut cream, and granola, a perfect combination to make you fall in love.",
        sunrise_d:"Interesting mix of flavors that will make you ask for more, dates, papaya, orange, flaxseed. Very aromatic and refreshing",
        mina_club_d:"To make you up in the morning, combine banana, oat milk, oatmeal, coffe shot, agave syup. It will activate your senses.",
        agua:"Water",
        natural_plastico:"Natural / plastic 330 ml",
        natural_vidrio:"Natural / glass 330 ml",
        refrescos:"Refreshments",
        whisky_sour:"Whisky Sowr",
        coctel_sabores:"Flavor Cocktail",
        ron:"Run",
        ginebras:"Gin",
        conac:"Cognac",
        conac_hennessy_special:"Cognac Hennessy Special",
        mezcales:"Mezcals",
        licores:"Liquors",

        cerveza:"Beer",
        cerveza_mina:"Mina Beer",
        cerveza_tulum:"Tulum Beer",
        bohemia_clara:"Bohemia Clear",
        bohemia_oscura:"Bohemia Dark",
        cubeta:"Bucket",
        cubeta_d:"6 national beers not including craft beers",
        vino_champagne:"Wine & Champagne",
        copa_vino:"Wine Glass",
        copa_vino_d:"White or Red. 150ml",
        botella_vino:"Bottle of Wine",
        copa_vino_espumoso:"Glass of Sparking Wine",
        botella_vino_espumoso:"Bottle of Sparking Wine",
        botella_champagne:"Champagne Mort Chanson",
        mixologia:"Mixology",
        mina_d:"A unique creatio with a blend of flavors that invite an unforgettable tasting experience. Dark rum, Disaronno, bitter bitters, salt solution, homemade tepache and mint leaves.",
        fresh_mandarin_d:"From our line a refreshing and powerful option ideal to start your MINA experience, garnished with a pigeon cone. Mezcal espadín, Aperol, mandarin orange, agave syrup, lime juice, rim of the glass with chili powder.",
        coconut_mojito_d:"We offer you a classic beach flavor, the coconut but presented with style. White rum, Malibu, coconut syrup, fresh lime, mint leaves and mineral water top.",
        fresco_doce:"Fresco12 Tiki Glass 300 ml",
        fresco_doce_d:"A refreshing explosion of tropical flavors and herbal touches that awaken the senses. Tequila blanco, pineapple/lemon cordial sour, agave syrup, arugula leaf and saline solution.",
        tropical_fig_d:"MINA's version of a Gin Fig, the one you can't pass up, dare to try it. Solferino Gin, Triple Sec, lemon juice, natural syrup and fig.",
        tecito_d:"An intriguing cocktail that combines the smoky with the fresh, creating an unexpected flavor experience. Mezcal espadín, frangelico liquor, green tea, lemon grass and lime juice.",
        passion_caipirinha:"For couples we offer this version of caipirinha, the passion fruit gives it that sensual touch you are looking for. Infusion Dirty Vodka, fresh lime, natural syrup, passion fruit pulp and mineral water dash.",
        devils_spritz:"A bubbly, attractive and delicious option, it's good company with seafood. Dirty Devil Vodka, Aperol, passion fruit, lemon juice, agave syrup, tonic water and Prosecco top.",
        reservas:"Make your reservations through:",
        comentarios:"Comments on:",
        siguenos_en:"Follow us on:"
        // Añade más claves y traducciones aquí
    }
};

function setLanguage(language) {
    if (language === 'es') {
        // Recargar la página o redirigir a la versión en español si es necesario
        location.reload();
    } else {
        // Selecciona todos los elementos dentro del grupo que tienen el atributo data-translate
        document.querySelectorAll('[data-translate]').forEach(element => {
            const key = element.getAttribute('data-translate');
            element.innerText = translations[language][key];
        });
    }
}

// No establecer el idioma predeterminado, ya que el español es el contenido por defecto en el HTML
